right_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_joint_2
    - right_joint_3
    - right_joint_4
    - right_joint_5
    - right_joint_6
    - right_joint_7
  gains:
    right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_joint_2
    - left_joint_3
    - left_joint_4
    - left_joint_5
    - left_joint_6
    - left_joint_7
  gains:
    left_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1